### ISSUE TITLE
Create the API credentials using python/CLI

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/Azure-Shell#10]
Check if its possible to create the API credentials using python/CLI. If not than we need an installation guide on how to do that.

http://confluence.quali.com/display/QP/Azure+API+Configuration

**Comment by alexazarh** [comment]
It should be possible to do this using Azure PowerShell CLI. Need to create a power CLI script that will do the following:
1. The tool should request the user crentials for Azure in a secure way
2. Print to the output the authentication tokens.

* Need to add confluence page to explain how to use this tool

The next step should be to copy the authentication tokens to the cloud provider resource.

**Comment by alexazarh** [comment]
We want to provide customers with 2 options: 
1. automatic tool
2. manual (using documentation)

**Comment by alexazarh** [comment]
We will investigate if its possible to create this using ARM template
