### ISSUE TITLE
Refactor azure_shell.py

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#100]
1. Move all operation creation to the ctr
2. move all parser calls under the error handling context manager
3. Make sure all commands have an error handling context manager

**Comment by apiddubny** [comment]
@alexazarh 
what is meant by
1. Move all operation creation to the ctr ?

**Comment by alexazarh** [comment]
It means to create the instances of the Operation classes in the constructor of AzureShell instead of creating a new instance of the operation for every command

**Comment by TomerAdmon** [comment]
No testing needed
