### ISSUE TITLE
Document instructions for AD user configuration for Azure-API

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/Azure-Shell#11]
As part of Azure installation guide we need to document how to configure Azure API with you AD user - see details here:
http://confluence.quali.com/display/QP/Azure+Configuration

**Comment by yairbb** [comment]
@TomerAdmon @TaiTheGreat @alexazarh 

The link is break.
Could you supply the correct reference ?

**Comment by TomerAdmon** [comment]
@Shnitselon - Steven, can you provide Yair the latest documentation for final review? (by email... not in here...)

**Comment by TaiTheGreat** [comment]
http://confluence.quali.com/display/QP/Azure+API+Configuration
