### ISSUE TITLE
Implement GetApplicationPorts (like in AWS)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#115]

**Comment by yairbb** [comment]
@GilGald , @alexazarh 
Pls provide relevant stories in AWS.

**Comment by alexazarh** [comment]
https://github.com/QualiSystems/AWS-Shell/issues/70

**Comment by tornizanQ** [comment]
[TestPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157704)
