### ISSUE TITLE
Prepare connectivity

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/Azure-Shell#12]
- [x] \* Manual configuration of the the management networking elements 
- [x] \* Implement the prepare connectivity for Azure: 
- [x]   \* Create resource group for the sandbox
- [x]   \* Create a storage resource for the sandbox
- [x]   \* Attach the default tags to all sandbox resources 
- [x]   \* Create a key pair for the sandbox and save it in the storage resource 
- [ ]   \* Create the subnet for the sandbox and the NSG object (configure the NSG to accept traffic from the management network), Deny traffic from other subnets in the sandbox vnet.
- [ ] *_Add only a subnet to the management VNET(the VNET should be already configured) ,add attribute on Cloud Provider management_group_name.  *_
  In the management_group_name. we will find the Management VNET and its Tags ,Cidr 
  It should contain the Tag:  Role = "Sandbox" and "Management"

http://prntscr.com/cw9cko

Architecture: 
http://confluence.quali.com/pages/editpage.action?pageId=26346704

**Comment by tornizanQ** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157106)

**Comment by tornizanQ** [comment]
Bug opened #149
