### ISSUE TITLE
GetAccesKey hidden command (like in aws)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#122]

**Comment by yairbb** [comment]
Pls provide reference to the relevant story in AWS.

**Comment by yairbb** [comment]
@alexazarh , @igoro1975 
Pls provide more details in order to cover it  from PV side

**Comment by yairbb** [comment]
@TomerAdmon  pls provide more details.

**Comment by TomerAdmon** [comment]
This command should work like the GetAccesKey in the AWS-shell. 
this is a hidden command (can remove the hidden tag in the driver metadata for testing) that should print the user the PEM file of the reservation.
aws related issue: [link](https://github.com/QualiSystems/AWS-Shell/issues/171)
aws code implementation: [link] (https://github.com/QualiSystems/AWS-Shell/blob/2c3684f2f89b0a70782c5eae71c15ecad36d58ad/package/cloudshell/cp/aws/domain/ami_management/operations/access_key_operation.py)

**Comment by alexazarh** [comment]
Test plan needed

**Comment by tornizanQ** [comment]
[TestPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157735)

**Comment by tornizanQ** [comment]
Waiting to test on custom image
