### ISSUE TITLE
QualiX Integration with Azure - server side

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#142]
In order for QualiX to fully support integration with every cloud provider we need to add the following functionality on the server side:
 
1. PrepareConnectivity will return in the command result the "access_key" for the reservation. 
2. "access_key" property should be considered as optional by the server.
3. In the server side we need to save the keypair data in the DB for a reservation. 
          - Need to create a new table for this (consult with shay about Naming).
          - Consider encrypting the data like we do for user password
4. On End Reservation we need to remove the keypaire from the DB

**Comment by TomerAdmon** [comment]
@yairbb , @tornizanQ  - Testing should be made on 7.1. make sure to run quick sanity on AWS as well since Igor will change some code in the PrepareConnectivity area.

**Comment by TomerAdmon** [comment]
This feature should be developed & Test only on top of CloudShell 7.2

**Comment by yairbb** [comment]
@TaiTheGreat @tornizanQ
