### ISSUE TITLE
Teardown is running forever and does not deletes the NSG

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#146]
STR
Have a reservation with azure vm 
End the reservation and wait for the teardown

BIR
The teardown is running forever and doesnot manage to delete the NSG

**Comment by tornizanQ** [comment]
raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: Error cleaning connectivity in reservation 'd67901b6-68e7-49aa-b6ab-c0f893cd0d43'. Error: Object reference not set to an instance of an object.

Parameters:
@igoro1975

**Comment by igoro1975** [comment]
Bug 159 fixes the last comment exception.
