### ISSUE TITLE
When trying to reserve an environment with 30 apps the setup fails

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#149]
STR 
Have environment with 30 apps
Reserve the environment and wait for the setup script to run.

BIR
when the setup script finished some of the apps been deployed corectly and some of them fails with the error:
"Queued command expired due to time-to-live timeout.
Parameters:"

![image](https://cloud.githubusercontent.com/assets/17527106/20244757/767c2c18-a996-11e6-9521-8093c88620e4.png)

Logs

[Ex Logs.zip](https://github.com/QualiSystems/Azure-Shell/files/587679/Ex.Logs.zip)
[Server Logs.zip](https://github.com/QualiSystems/Azure-Shell/files/587680/Server.Logs.zip)

**Comment by tornizanQ** [comment]
Cannot reproduce with the same error as before, now it seems related to the public IP. 
The current error received:
StaticPublicIPCountLimitReached
Message: Cannot create more than 20 public IP addresses with static allocation method for this subscription in this region.

**Comment by alexazarh** [comment]
Should be resolved when using the enterprise account
