### ISSUE TITLE
Disk Type support in Azure app

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#153]
Need to add support for selecting Disk Type when deploying an Azure VM.

- Note that the attribute Disk Type already exist on the deployment service. 

- Need to set value restriction to the following values: "SSD/HHD"

- This attribute should have the same functionality as the following option in the UI:
![image](https://cloud.githubusercontent.com/assets/6730546/20245877/623124a8-a9b3-11e6-9c1d-1724061df674.png)

**Comment by igoro1975** [comment]
The Azure UI offers as default value SSD disk type. I'll do the same for us.

**Comment by alexazarh** [comment]
👍

**Comment by igoro1975** [comment]
1. Azure does not support SSD for the Standard accounts.
2. Quali supports only Standard accounts.
3. The "Disk Type" attribute is removed

**Comment by TomerAdmon** [comment]
In 7.1 we only support Standard storage accounts, in this type of account, there is no option to deploy SSD, so for now we don't need this option in the UI. we will consider adding it for later releases.
