### ISSUE TITLE
Azure app names after deploy are mess

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#156]
![image](https://cloud.githubusercontent.com/assets/17527106/20246189/57b5ce46-a9ba-11e6-97a2-1cddf7fb1395.png)

**Comment by igoro1975** [comment]
@tornizanQ what do we expect to see? The same name? What if more than one app is deployed?

**Comment by tornizanQ** [comment]
Azure_VM18.... and after rest of the name
Like in AWS or vCenter
