### ISSUE TITLE
QualiX Integration with Azure - shell side

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#157]
In order for QualiX to fully support integration with every cloud provider we need to add the following functionality on the Azure shell side:
- PrepareConnectivity command should return in the result json the "access_key" (private key) strings for the reservation.
- The "access_key" must be encrypted.

We need to add a public key to the ES that the shell will be able to use to encrypt data. And a private key on the server side that the server will use for decryption.

Resources:
http://www.laurentluce.com/posts/python-and-cryptography-with-pycrypto/

**Comment by TomerAdmon** [comment]
This feature should be developed & Test only on top of CloudShell 7.2

**Comment by yairbb** [comment]
Will be tested in issue #251

**Comment by yairbb** [comment]
@TaiTheGreat @tornizanQ
