### ISSUE TITLE
Improve performance of prepare connectivity

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#160]
We can create some of the object asynchronously and wait in the end instead of creating all the objects one by one

**Comment by alexazarh** [comment]
We can do a few more things to speed up the prepare connectivity. 
1) We can create the storage account + keys in a separate thread and join it in the end - we should do this change now.
2) Create the NSG in async mode and create the subnet without the NSG. After both are done update NSG on subnet. This change is more risky so we will consider doing it later.

**Comment by tornizanQ** [comment]
Is there any suggested way to check it or to compare it to something?

**Comment by alexazarh** [comment]
@tornizanQ 
Not at the moment. I think we can move this to done.
We have a different item in the board for creating performance baseline. Once we have his we will be able measure performance improvements.
