### ISSUE TITLE
Add description to all attribute in autoload

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#169]

**Comment by yairbb** [comment]
@TomerAdmon 
Reminder to write the proper description for that

**Comment by yairbb** [comment]
This is the link:

http://confluence.quali.com/pages/viewpage.action?pageId=18514287

**Comment by yairbb** [comment]
@TomerAdmon  Pls summerize all the relevant tickets to one.

**Comment by TomerAdmon** [comment]
This issue is included in #59 ... closing
