### ISSUE TITLE
Password attribute is returned in clear text

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#175]
The data that we return from the deploy command is visible in clear text in the reservation activity feed. 
We need to return the password attribute as the encrypted string that we get from the app data json (The knows how to handle the encypted password).
If we are generating the password on our own in the shell than we should return it as clear text for the moment because there are no other alternatives available.

**Comment by alexazarh** [comment]
If printOutput=False when executing command than we are going to hide the command result in the activity feed and this will solve the problem

**Comment by alexazarh** [comment]
Will be fixed in trunk & 7.1

**Comment by yairbb** [comment]
fixed!
