### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#178]
make sure all images make sense in the shell

**Comment by yairbb** [comment]
@TomerAdmon 

pls supply more details. :-)

**Comment by TomerAdmon** [comment]
We are missing:
- Cloud provider icon
- deployment options icon for deploy & custom deploy

waiting for icons...

**Comment by alexazarh** [comment]
Icons for 2 deployment options
[Icons_Deployment_Type_azure.zip](https://github.com/QualiSystems/Azure-Shell/files/649066/Icons_Deployment_Type_azure.zip)

**Comment by yairbb** [comment]
@alexazarh @TomerAdmon 

even it is simple :-)

I prefer to   write Test plan with the needed images attached inside the test case.

**Comment by alexazarh** [comment]
Icon for CP
[azure_cp_icon.zip](https://github.com/QualiSystems/Azure-Shell/files/659369/azure_cp_icon.zip)

**Comment by Shnitselon** [comment]
deployment type images updated in Managing Apps>Adding Apps> step 1 image
