### ISSUE TITLE
Possible to use the shell when venv is on

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#198]
currently we are all working / testing with the virtual environment feature turned off. Customers will use this feature most of the times so we need to be sure that all shell functions are working with it.

**Comment by TomerAdmon** [comment]
currently waiting for Ronen.a scrum to fix 157472

**Comment by tornizanQ** [comment]
msrestazure - missing package when using venv 
maybe need to add to requirement
