### ISSUE TITLE
Support image version

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#201]
currently we always use the 'latest' version of an image, we would like an attribute that is not a user input and can be used to override the 'latest' option.
The new attribute will have a default value of "latest".

**Comment by TomerAdmon** [comment]
@yairbb  - few test cases should be added to the "deploy VM from marketplace" test plan 156068

**Comment by yairbb** [comment]
@TomerAdmon 

Description is missing.  you dont think we have to add it in case it will be user input ?

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=158288]

**Comment by TomerAdmon** [comment]
@yairbb - description for "Image Version" :  "The version to the Azure image.For Example: 16.04.201606270"
also added to confluence.
