### ISSUE TITLE
Azure shell driver requirement is missing "msrestazure" pack

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#210]
Azure shell driver requirement.txt is missing "msrestazure" pack

@alexazarh @GilGald

**Comment by alexazarh** [comment]
@tornizanQ it should be a dependency of the main azure package. What error are you getting?

**Comment by TomerAdmon** [comment]
@tornizanQ  - please add logs so we can prioritize this issue....
