### ISSUE TITLE
Custom Image Description

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#217]
Correct description shell be supplied to the next fields:"IMAGE OS TYPE" and "IMAGE URN".

Currently both of them are missing.

**Comment by alexazarh** [comment]
@TomerAdmon please provide the description text for "IMAGE OS TYPE" and "IMAGE URN" attributes

**Comment by yairbb** [comment]
@TomerAdmon @alexazarh 

the description of "Azure Subscription ID"  is  missing  too. pls provide.

**Comment by TomerAdmon** [comment]
@yairbb  - I don' think we need description for "Azure Subscription ID" field...

**Comment by yairbb** [comment]
why ? since it is understandable from the name ? it will be the only field without description. so, what do you think ?
