### ISSUE TITLE
VXLAN support

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#218]
add support for VXLAN allocation range in the server.
Add attribute with the name "Vlan Type" that have two optional values "VLAN / VXLAN"/
If the attribute set to VXLAN the allocation rang ein the server will be set to 16 milion addresses. if VLAN it will be set to 4096.
the default value is VLAN and if the attribute doesn't exist the server will use the VLAN range.

Documentation. needed
Add the attribute to the OpenStack shell
No other changes to any shells needed

**Comment by alexazarh** [comment]
Also update the name of the vlan service when we are in vxlan mode accordingly so that it will be clear that is a vxlan, like: "VXLAN 5"

**Comment by GilGald** [comment]
@TomerAdmon / @doppleware 
What should we do if we have P2P scenario in which we have 2 different connectivity providers and each one with a different Vlan Type?
Should we throw an error or we should check if the VXLAN allocation range is inside the VLAN allocation range?

**Comment by TomerAdmon** [comment]
@GilGald  - it's not likely that this kind of scenario will happen in real labs. we would like to block it and make sure that an error will be thrown to the user just in case someone had a mistake along the way.

**Comment by tornizanQ** [comment]
[testPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement?planId=125053&suiteId=158841)
