### ISSUE TITLE
Setup fails to run in the middle of preper connectivity

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#223]
STR 
have an environment with azure app
reserve the environment 

BIR
Error:
unbound method encrypt() must be called with RsaService instance as first argument (got str instance instead)
Parameters:

[logs.zip](https://github.com/QualiSystems/Azure-Shell/files/630211/logs.zip)

**Comment by alexazarh** [comment]
Fixed by pr #224
