### ISSUE TITLE
Useablity : Inbound shell be active only if Public IP is True

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#225]
In case "Add Public IP" field is false and "Inbound Port" isn't empty, "Active In Error" is obtained during the deployment.

From the customer side it will be problematic to know that only after the deployment was finished (with Error)

It will be better to make "In bound port" Active only in case "Add public IP" is set to true. At the other hand it will not be available for user input.

**Comment by TomerAdmon** [comment]
There are use cases where you want machines without public IP and with inbound ports... for example, if you have a website you want to test in your sandbox and it isn't exposed to the internet, it should still be open in port 80/443 to the testing environment in the sandbox with that port....

**Comment by yairbb** [comment]
but you will not be able to deploy the App it will get back to you with Error if the Add public IP set to false ?

**Comment by alexazarh** [comment]
@TomerAdmon Connectivity between apps in the sandbox is unrestricted. It means that if you want to use some web app and only access it from the sandbox you can do this without thhe need to opening the port.
The "inbound ports" attribute is used to allow traffic from outside the sandbox.

**Comment by alexazarh** [comment]
@TomerAdmon Connectivity between apps in the sandbox is unrestricted. It means that if you want to use some web app and only access it from the sandbox you can do this without thhe need to opening the port.
The "inbound ports" attribute is used to allow traffic from outside the sandbox.
@yairbb This is the way it was designed. You need to configure the app correctly...

**Comment by TomerAdmon** [comment]
We have it pretty much covered in the attribute descriptions, so it seems ok.
