### ISSUE TITLE
Support Virtual machine extension

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#247]
As a user i would like to deploy a new virtual machine (Linux or Windows) with "Azure custom script" extension. 
We would like to support only "Custom script" that will be a powershell script on Windows and a bash script on Linux. the script can be used from online location (http/https link) or directly from the execution server (/etc/....).
We will add the script execution as another step in the deployment phase(deployment request)  for the Azure app deployment. 
Results / output / failures should be presented as in the Azure Portal UI. I't probably impossible to see the ouput in the UI / API, as documented here: https://github.com/Azure/custom-script-extension-linux.

**Comment by alexazarh** [comment]
Maybe we also need an attribute for arguments

**Comment by TomerAdmon** [comment]
please note that when using the Script extension for Linux, it's possible to use more then one script file.

Attributes names & Descriptions:
Name: Extension Script file
Description: The path to the script files that will be downloaded to the virtual machine. For Linux machines, it’s possible to use more than one script file. Example: https://gist.github.com/ahmetalpbalkan/b5d4a856fe15464015ae87d5587a4439/raw/466f5c30507c990a4d5a2f5c79f901fa89a80841/hello.sh


Name: Extension Script Configurations
Description:Additional information for the extension execution.
For Linux machines, The command to execute, for example: python MyPythonScript.py input1 input2.
For Windows machines, The PowerShell script arguments(Optional), for example: --input1 value2 –input2 value2.

**Comment by TomerAdmon** [comment]
According to the Linux extension GitHub page, those are supported Linux Distributions
CentOS 6.5 and higher
Debian 8 and higher
FreeBSD
OpenSUSE 13.1 and higher
Oracle Linux 6.4 and higher
SUSE Linux Enterprise Server 11 SP3 and higher
Ubuntu 12.04 and higher
https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript

**Comment by yairbb** [comment]
@TomerAdmon @alexazarh 

I assume that there is no meaning to the Linux distributions type. correct ? or you prefer to choose specific one or some  from the list ?

**Comment by TomerAdmon** [comment]
I think CentOs will be OK

**Comment by tornizanQ** [comment]
[testPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=158311)

**Comment by tornizanQ** [comment]
blocked by https://github.com/QualiSystems/Azure-Shell/issues/327

**Comment by tornizanQ** [comment]
blocked by #369
