### ISSUE TITLE
Description:KeyPair location

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#252]
Description shell not refer to S3:"Verify: "The name of an S3 bucket in which PEM files will be located. Each active Sandbox will have a PEM file under a designated folder. For example "sandbox-management""

**Comment by alexazarh** [comment]
@yairbb I dont understand this bug?
We dont have an attribute that refers to keypairs location in azure...

**Comment by yairbb** [comment]
You R Right.

Tomer commented it out after I took it.
