### ISSUE TITLE
Description Error:  Inbound Ports.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#256]
The description is not aligned correctly to RM.

**Comment by TomerAdmon** [comment]
Didn't get you... can you elaborate?

**Comment by yairbb** [comment]
There is a mismatch between confluence to RM.
I took the description from conf before it's failure.

Both of description look ok but not the same.
conf:"Ports and protocol to open for inbound traffic. Note that all ports are open for traffic within the Sandbox. The syntax is "protocol[tcp(default)/udp]:port[single/range]" with semi-colon separation, for example: "80;tcp:443;udp:200-220"."
"
RM:"Ports and protocol to open inbound traffic from outside of the sandbox. The syntax is port[single/range]:protocol [tcp(default)/udp] with semi-colon separation, for example: 80;443:tcp;200-220:udp."

**Comment by yairbb** [comment]
fixed!
