### ISSUE TITLE
Change Tenant attribute

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#258]
Need to change the Tenant attribute so it will be aligned with the other attribute names.

Change "Azure Tenant" to "Azure Tenant ID"

**Comment by apiddubny** [comment]
@alexazarh 
should we also change "Azure Secret" to "Azure Secret ID"?

**Comment by alexazarh** [comment]
No need since the secret is like a password and not an ID of an object

**Comment by apiddubny** [comment]
@alexazarh 
for "Azure Tenant ID" we have the next description "Typically a name of an organization, which uses the cloud services created and provisioned by a hosting service provider."

Maybe  we also need to update description with ID?

**Comment by alexazarh** [comment]
@apiddubny Yes that makes sense.
@TomerAdmon - FYI

**Comment by apiddubny** [comment]
@alexazarh @TomerAdmon 
please update confluence/paste here the updated version of description

**Comment by TomerAdmon** [comment]
Hi, here is the new description, also updated in confluence:
"""The Azure tenant Id that is associated with your Azure Active Directory (AAD) instance. For example: ccd13026-98e3-4e90-01f4-28e2afdf3213. This GUID can be retrieved using Azure CLI"""
