### ISSUE TITLE
Change Cloud name and deployment option name

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#259]
We should change the Cloud provider name from "Azure" to "Microsoft Azure" and the "Azure VM" deployment type to be "Azure VM from Marketplace"

**Comment by TomerAdmon** [comment]
please make sure to sync with @cohoren  since tests will probably fail...

**Comment by Shnitselon** [comment]
For consistency with other deployment types, we should use "Azure VM From Marketplace" (uppercase "From") or make all instances of that word lower case
