### ISSUE TITLE
Refresh IP Command

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#26]
Refresh IP command should be available on deployed apps. (Connected command from the Azure resource)

Input: None

The command should connect to the Azure API and retrieve the private and public IPs, and then update the resource details in CloudShell. 

Private IP - the resource address
Public IP - attribute on the deployed app resource
- need to configure the NSG rules in case the public IP was updated if there are open ports - moved this part to a different story #63

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156377)
