### ISSUE TITLE
Region attribute on the cloud provider accepts only lower case

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#260]
Region attribute on the cloud provider accepts only lower case without space 

Exepected: 
Should accepts both lower and upper case and with space in the middle
"East Canada", "east canada" and "eastcanada"

**Comment by alexazarh** [comment]
It looks like the solution for is simple use lower case on the region attribute

**Comment by TomerAdmon** [comment]
can't we lowercase-it always in the code?

**Comment by alexazarh** [comment]
Yes of course this is what I meant :)
