### ISSUE TITLE
Teardown not always deletes the subnet of the reservation

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#263]
STR
Have a reservation with deployed app 
wait the reservation to end 

BIR
if something fails in the middle of the teardown the subnet not always erase

**Comment by TorNizan** [comment]
[logs.zip](https://github.com/QualiSystems/Azure-Shell/files/651827/logs.zip)

**Comment by tornizanQ** [comment]
Also occurs when setup fails after the app already deployed (fail to power on for example), there is no error in the teardown

**Comment by apiddubny** [comment]
@tornizanQ 
What is this bug about? That subnet must be deleted event if some of the VM deletion operations failed?
According to logs there is some bug inside delete_azure_vm (from logs.zip):
CloudError: Azure Error: AnotherOperationInProgress (which is not related to the subnet)

**Comment by GilGald** [comment]
@apiddubny 
we need to verify that the subnet is deleted. In the code add a wait until the the operation ends. result.wait() I think...

**Comment by tornizanQ** [comment]
Able to reproduce If I end the reservation at the beginning of the setup script, there is no error in the logs or in the activity feed

**Comment by alexazarh** [comment]
It will be fixed by #302
