### ISSUE TITLE
Custom Image Credentials

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#264]
@TaiTheGreat @apiddubny 

No option to connect VM which was created from Custom Image App.

**Comment by TomerAdmon** [comment]
Please provide steps to reproduce, expected result and actual result.

**Comment by yairbb** [comment]
Ok,

I will do that.

Did you grant Tai ? (waffle)

**Comment by TaiTheGreat** [comment]
STR:

1. Create a custom image app with a public IP and port 22 inbound.
2. Give it a username and valid password (at least 6 chars, uppercase, lowercase and numeric).
3. Deploy the app. 
4. Try to SSH using the credentials. 

Expected: successful connection. 
Actual: access denied.
