### ISSUE TITLE
# reservation Active with Error when the name of the app name is long

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#269]
Run this script :

for i in range(0,3):
    session.CreateImmediateTopologyReservation('Demo_test'+str(i),'admin','30',False,False,'0','Demo')

make sure that the name of the app in the reservation is very long like : azureapp11111111111111111111111111111111111111

2 of the 3 reservations are going to fail on power on.
The cause for this error is that the name allocation is not working as expected and the deployed apps are created with different name then the name in the resource group

**Comment by tornizanQ** [comment]
Talk to @GilGald

**Comment by TomerAdmon** [comment]
cant you attach some logs?

**Comment by TorNizan** [comment]
[Azure--14-Dec-2016--17-26-31 - Copy.zip](https://github.com/QualiSystems/Azure-Shell/files/652126/Azure--14-Dec-2016--17-26-31.-.Copy.zip)
