### ISSUE TITLE
Windows - OS credentials

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#27]
App configuration may have in the information about the OS creadentials for the App - as attributes on the Deployed App Model (available from the App advanced section). 

For windows VMs: 
- If the App request do not define the user & password -> VM credentials: u:adminuser p: [auto generated]
- If the App request defines the user (without password)-> VM credentials: u:[requested user], p:[auto generated]
- If the App request defines the user & the password -> VM credentials: u: [requested user], p:[requested password]
- If the App request defines the password (without the user)-> VM credentials: u:adminuser, p:[requested]

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156412)

**Comment by TomerAdmon** [comment]
reopen for documentation
