### ISSUE TITLE
Hybrid Test: On-pem QualiServer using VPN to access Execution Server on Azure

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#272]
Testing only.

install Cloudshell on the office network, use Execution server without public ip in Azure to deploy vms.

**Comment by yairbb** [comment]
@tornizanQ 

Add specific test case to connectivity TP to cover this case.

**Comment by TomerAdmon** [comment]
https://qualisystemscom.zendesk.com/agent/tickets/29235
