### ISSUE TITLE
Linux - OS Credentials & OpenSSH key pair

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#28]
App configuration may have in the information about the OS creadentials for the App - as attributes on the Deployed App Model (available from the App advanced section). 

For Linux VMs: 
- If the App request does not define the user & password -> VM credentials: u:adminuser, p: not needed (connectivity by key pair)
- If the App request defines the user (without password)-> VM credentials: u:[requested user], p: not needed (connectivity by key pair)
- If the App request defines the user & the password -> VM credentials: u: [requested user], p:[requested password]
- If the App request defines the password (without the user)-> VM credentials: u:adminuser, p:[requested]

the key pair is generated in the 'prepare connectivity' phase and saved when creating a storage account for the sandbox. 
When deploying the vm, the key pair that is passed to the Azure API should be taken from the sandbox storage resource.

**Comment by tornizanQ** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157068]

**Comment by TomerAdmon** [comment]
reopen for documentation
