### ISSUE TITLE
S3 cleanups

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#282]
1) Get an official account from Shelomi for S3
2) Move all our content to be in specific bucket in S3 (ES & QX).
3) Place Templates & CloudFormation in the S3 bucket
4) update CloudFormation & Template to use the new location
5) update documentation if needed

#Testing needed: sanity for CloudFomration & Azure Template

**Comment by TomerAdmon** [comment]
http://confluence.quali.com/display/QP/S3+structure+for+cloud+provider+dependencies

**Comment by GilGald** [comment]
Remember to Get the new location of the QualiX and update the CF and templates

**Comment by alexazarh** [comment]
Test plan is not needed here, it will be checked as part of the templates test plan.

**Comment by TaiTheGreat** [comment]
Waiting for #454
