### ISSUE TITLE
Teardown failure with multiple azure resources

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#283]
1. Create a sandbox with 20 azure custom images (this probably also happens with less, but do 20 just in case). 
2. After setup has completed (with no errors), end the sandbox. 
3. Wait for teardown to finish.

BIR if some resources were not deleted from the sandbox (but the resource group and all VMs were deleted from the Azure portal).

The following error was taken from the logs:
2016-12-18 09:33:35,291 [58] ERROR RemoveDeployedResource - [IP: ::1, Machine: QS-IL-TAI:8029 - Tcl, QualiSystems Username: admin]
Could not delete deployed resources: 
azurecus85f8d3b5cf814708: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/ce1d08e3-12ba-40bc-9bd2-29e1c8b28030?api-version=2016-06-01.
azurecusd42afc3b205546b4: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/cafb08e2-f33f-467c-8467-bb88a7317811?api-version=2016-06-01.
azurecus1f394f2d5cd8489c: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/b5f92e7a-fd9c-4247-92aa-482147521dec?api-version=2016-06-01.
azurecus66a0691f6c844130: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/8cb2fae0-d5f4-460b-954e-4d456b1efe5e?api-version=2016-06-01.
azurecus856850b44b0d46c5: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/4da548bf-b514-4d75-aaf3-cd8a48874526?api-version=2016-06-01.
azurecus716df878b8ca485f: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/4da548bf-b514-4d75-aaf3-cd8a48874526?api-version=2016-06-01.
azurecuse9e5b1d7c1d34f43: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/320cce38-71a4-4f01-8f9b-b2a6402a798e?api-version=2016-06-01.
azurecus73385cbae52844bd: CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/providers/Microsoft.Network/locations/northcentralus/operations/346294ff-9c22-4d73-aaf4-de04abce047e?api-version=2016-06-01.
azurecusa0855975f1b44310: CloudError: Azure Error: RetryableError
Message: A retryable error occured.
Exception Details:
	Error Code: RetryableErrorDueToAnotherOperation
	Message: Operation DeleteSecurityRuleOperation (aa2c9e0b-583f-4974-9645-e866de6b5535) is updating resource /subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/resourceGroups/6c581aaf-e5e1-4fb0-92d9-27ddc3789f1c/providers/Microsoft.Network/networkSecurityGroups/6c581aaf132ae945c4814291. The call can be retried in 14 seconds.
	Target: None

2016-12-18 09:33:39,518 [58] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TAI:8029 - Tcl, QualiSystems Username: admin]
RemoveDeployedCommandException [Error Code: General] [Original Time: 2016-12-18 09:33:39,514]: Could not delete the following resources: azurecus85f8d3b5cf814708,azurecusd42afc3b205546b4,azurecus1f394f2d5cd8489c,azurecus66a0691f6c844130,azurecus856850b44b0d46c5,azurecus716df878b8ca485f,azurecuse9e5b1d7c1d34f43,azurecus73385cbae52844bd,azurecusa0855975f1b44310
   at QualiSystems.ResourceManagement.Service.DomainService.Reservation.ReservationDomainService.RemoveDeployedResource(Reservation reservation, Guid[] deployedResourcesToRemove)
   at QualiSystems.ResourceManagement.Service.Domain.ReservationApplicationService.RemoveDeployedResourceFromReservation(Guid reservationId, Guid[] deployedResourcesToRemove)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ReservationAPIApplicationService.RemoveResourcesFromReservation(Guid reservationId, String[] resourcesFullName)

**Comment by alexazarh** [comment]
The subnet locker in the delete operation should be shared with the subnet locker in prepare connectivity

**Comment by alexazarh** [comment]
And also the generic locker is not used when removing security rules
