### ISSUE TITLE
Basic deploy of an Azure app

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/Azure-Shell#3]
- ability to create a Azure cloud provider in the Inventory (no need for shell template yet)
- new deployment option "Azure VM" with the required attributes
### Flow that should be supported:
- [x] > 1. create "Azure" cloud provider
- [x] > 2. fill in "Azure" cloud provider attributes
- [x] > 3. create new app and select "Azure VM" deployment option
- [x] > 4. point to "Azure" cloud provider resource via attribute
- [x] > 5. fill in deployment attributes - VM image, additional required parameters
- [x] > 6. create an environment, add the app from the catalog and reserve
- [x] > 7. setup should deploy the app
- [x] > 8. once the app is deployed it should be already powered on and have its private ip as the address
### Notes:
- [x] > (a) the creation of the virtual network, subnet and SG is all in advance so we should have temporary attributes on the cloud provider resource with their information. --> prepare connectivity isn't implemented yet
- [x] > (b) custom ports to open not supported in this stage
- [x] > (c) public ip not supported in this stage
- [x] > (d) all other commands (power on/off, delete etc.) should be mocked so Setup won't fail
- [x] > (e) although the VM is powered on at the end of this flow the live status isn't updated yet, this will happen in #5
- [x] > this story should include tagging, same tags as in AWS

data model (not finalized!) can be found here:
http://confluence.quali.com/pages/viewpage.action?pageId=18514287

**We should create the Private IP as a dynamic IP add  after it's created(after the VM is created) and the IP allocated we should change the IP to Static with the IP we got.**

![](http://www.axonize.com/wp-content/uploads/2016/05/Azure_.png)

**Comment by yairbb** [comment]
Test Plan

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement%23planId=125053&suiteId=156068)

**Comment by GilGald** [comment]
## Mini Tasks
- [ ] Create a data model with all the attributes
- [ ] Create the Deployment driver
- [ ] Create the Shell Driver 
- [ ] In the basic flow we should create a Vm only ? What about the storage and the networking?

After the deployment finished we should verify that the resource is created in the Cloud Shell with the right Attributes.

**Comment by GilGald** [comment]
Some open things:
in the create_network_interface method the cidr's are magic Sstrings.
when does the the admin user and password should be generated?

**Comment by GilGald** [comment]
Add attribute for the instance size(basic_a02...), Hard Disk type: SSD\HDD
refactor the services and clients
