### ISSUE TITLE
Add cancellation support

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#302]
Add cancellation support to "prepare connectivity" and 2 deployment options.

** Once the reservation is eneded we have 2 minutes to complete all running commands that support cancellation before the teardown starts to run.

** For the vm deployments we probably need to create a custom waiter that will support cancellation (like we did in vCenterShell) because its a long operation. The custom waiter should poll every 30 sec by default.
Other api calls are shorter so its ok to use the sdk waiter and check the cancellation token between the calls.

** No need to add rollback in Prepare Connectivity. But need to make sure that in case of cancellation during Prepare Connectivity or Deploy the Cleanup will be able to remove all resources successfully.

**Comment by yairbb** [comment]
@tornizanQ 

Tor , Pls check affects on Prepare connectivity, delete TP.

**Comment by alexazarh** [comment]
And also deploy
