### ISSUE TITLE
Teardown not clear the Storage account and NSG

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#303]
TearDown shell delete all the VM's connected objects including the Storage Account and NSG.

Currently: both of them weren't deleted from Azure Portal.

**Comment by alexazarh** [comment]
please add logs

**Comment by TomerAdmon** [comment]
@yairbb  - if not reproducible, please cancel

**Comment by yairbb** [comment]
looks like it was solved!
