### ISSUE TITLE
Add Public IP - AWS vs Azure

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#310]
In AWS the default value of the "Add Public IP" was true but on Azure it's false....

**Comment by TomerAdmon** [comment]
@alexazarh  - what do you think?

**Comment by alexazarh** [comment]
@TomerAdmon I think its better to be false

**Comment by TomerAdmon** [comment]
@yairbb  - let's make sure it's false by default in Azure and open an issue for AWS to change it to be false, we wont fix it now, low priority....

**Comment by yairbb** [comment]
Done!
