### ISSUE TITLE
Terminology of the tags, Environment\Reservation Blueprint\Sandbox

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#314]
@TomerAdmon

**Comment by TomerAdmon** [comment]
We would like to change it to be "blueprint" and "sanboxId", it will require also a documentation fix...

**Comment by TomerAdmon** [comment]
Only in Azure for now.
added a tentative issue on AWS for the future. https://github.com/QualiSystems/AWS-Shell/issues/312

**Comment by TomerAdmon** [comment]
Please update the tags test plan and re-run relevant test cases
