### ISSUE TITLE
VM Size Input

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/Azure-Shell#315]
The input shell be like :"Standard_DS1_V2" as mentioned in description.
In portal the size appear like that :"D1_V2 Standard". This will cause error in deployment.
there is place to Re-think regarding that in order to  prevent failure in customer deployments.

**Comment by TomerAdmon** [comment]
@yairbb - Thanks Yair, we are familiar with this issue, but currently we don't have a good solution for that.. let's talk in the planning/grooming.

**Comment by yairbb** [comment]
@TomerAdmon 

Ok. 
Besides that i failed to deploy with the size given in the description.

I assume that you it from azure portal/cli. Is that depends on the VM type ?

**Comment by TomerAdmon** [comment]
you can see here all valid options here:  https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-sizes

The error was understandable?

**Comment by TomerAdmon** [comment]
Thanks Yair.
we should change the description, it's currently using a SKU family and not an actual size.
@alexazarh  - let's use the link inside the description. @yairbb - please validate the the description is correct and the link works.

also updated in confluence

The Microsoft Azure VM size. The VM size determines the CPU, memory and networking capacity of the VM. For example: “Standard_A2m_v2”. Use the Azure CLI or the Azure documentation for more information.

**Comment by alexazarh** [comment]
I updated the description slightly. Please look in confluence for latest version.

**Comment by yairbb** [comment]
Verified!
