### ISSUE TITLE
DOCUMENTATION ONLY: When deploying an app in a reservation the value of the owner tag will be the name of the reservation owner

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#317]
DOCUMENTATION ONLY:
When deploying an app in a reservation the value of the owner tag will be the name of the reservation owner.

**Comment by Shnitselon** [comment]
Added the following note to the "owner" tag description in the azure cost management topic:

"The report includes sandbox owners only. Permitted users who modified existing sandboxes are not included."
