### ISSUE TITLE
Additional NSG configuration on CP

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#322]
As a user i would like to be able to have an existing VNet with resources i'm already using in my Azure account (For example: TeamCIty server), it's required that this VNET will have connectivity to instances inside the sandbox in all ports after the deployment.
In order to implement this feature we will need to add a new attribute on the cloud provider that will not be a user input by default. this attribute will get the CIDR or the VNET we will would like to accosiate with our sandboxes and during the deployment it will be added to the NSG of the subnet.
notes:
The attribute is a user input
The attribute should be a comma-separated list of CIDRs
priorities for the rules should be dynamically between 3900-4000 (some of them is already taken)

Attribute name:
Attribute description:

**Comment by TomerAdmon** [comment]
Description: List of comma-separated networks in a CIDR manner that will be allowed to interact with all Sandbox instances. This is used for allowing connectivity to resource outside the CloudShell Mgmt network that should be available to the Sandbox Instances.

**Comment by alexazarh** [comment]
Lets use increments of 5 for priority

**Comment by yairbb** [comment]
@TaiTheGreat 

Pls add link to the TP.

**Comment by TaiTheGreat** [comment]
http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=158411
