### ISSUE TITLE
When using extension path that is not valid the app will not finish deployment

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#327]
STR
Have azure app in environment 
add to the EXTENSION SCRIPT FILE  a local path
Reserve the environment 

BIR
The app will try to deploy for more than 50 min.

**Comment by TomerAdmon** [comment]
do you get anything in the extension log inside the machine?

**Comment by tornizanQ** [comment]
I will look for it tommorow, as for now it is also accrues when there is a problem within the script itself

**Comment by yairbb** [comment]
I hope you didnt wait 50 mins for the App to be deployed :-)

**Comment by GilGald** [comment]
@TomerAdmon  Should we had an attribute that will decide whether we should wait until the execution of the deployment is finished?

**Comment by TomerAdmon** [comment]
For this release we will support only sync mode. no need to support async mode...

**Comment by TomerAdmon** [comment]
@GilGald , @alexazarh , @tornizanQ  - We do need to make sure, that in 7.1 timeout in the extension will not fail the deploy of the app, so a resource will be created in the sandbox and the user will be able to connect to the resource to see the output of the failed extension.
In 7.2 / 7.3 we will supply a proper solution for that.

**Comment by GilGald** [comment]
+We should add an attribute :Extension Script Timeout ,this should be hidden and on both Deployment  options (custom and market place).default value should be :20 min.
+when we get a timeout we should write to the output window in the portal and logs.

**Comment by TomerAdmon** [comment]
output should be the following:
<span style='color: red;'>App {{app name}} was partially deployed - Custom script extension reached maximum timeout of {{timeout}} minutes.</span>

**Comment by tornizanQ** [comment]
Test cases has been added to test plan (GIT #247) Support Virtual machine extension
