### ISSUE TITLE
Azure Template cleanups

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#338]
Please rename the existing resources to use the below names:

Virtual Networks:
CloudShell-Management-VNet
CloudShell-Sandbox-VNet

Network Security Group:
Execution-Server-NSG
QualiX-NSG

Virtual machine:
Execution-Server-VM
QualiX-VM

Public IP Adress:
QualiX-Public-IP

Network Interface:
Execution-Server-NIC
QualiX-NIC

Extension script:
Execution-Server-Script
QualiX-Script

Storage account:
CloudShell-Storage-Account

VPN:
Public IP: CloudShell-VPN-Public-IP
Local Network Gateway: CloudShell-VPN-Local-Gateway
Virtual Network Gateway: CloudShell-VPN-Virtual-Gateway

If it's also possible please rename the below tasks names:
Rename ‘qxDeployment’ to be “QualiX-Deployment”
Rename ‘vpnDeployment’ to be “CloudShell-VPN-Deployment”

**Comment by apiddubny** [comment]
@TomerAdmon 
Storage account: CloudShell-Storage-Account

storage account name must contain only lowercase letters and numbers. Besides, it must be unique per subscription. For now this value looks like "storage228c23314"
So do we need to change something here?

**Comment by TomerAdmon** [comment]
OK, le'ts keep the storage like it is now... 
@Shnitselon - please update documentation if needed

**Comment by Shnitselon** [comment]
we're good
