### ISSUE TITLE
Update the deploy to use the sandbox connectivity

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#34]
- Need to find the right subnet that was created for the sandbox during setup "prepare connectivity" phase 
  and connect the deployed vm to the subnet.
- If an app is added to an active reservation (that doesn't have a subnet), when trying to deploy return an error message (same as AWS) 
- If a subnet exists - deploy and connect to that subnet. 

Checking the subnet is done by connecting to the Azure API and retrieving the info according to the reservation id tag.

**Comment by igoro1975** [comment]
After consulting with @GilGald the task is postponed due to changes for subnets,

**Comment by igoro1975** [comment]
Seems that there is no additional development should be done.
