### ISSUE TITLE
os_type check in the shell not always working

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/Azure-Shell#343]
Try to deploy the a new APP with these Parameters about the VM:

publisher: MicrosoftVisualStudio
offer:    Windows
sku:  Windows-10-N-x64

from what i see the type returned in the os type is inconclusive  its linux and windows  (?),
and because of that the validate_script_extension functions fails :(

**Comment by GilGald** [comment]
@alexazarh  @igoro1975  what do you guys think?

**Comment by alexazarh** [comment]
I cant reproduce this
