### ISSUE TITLE
Testing: authentication for machine deployed form custome image

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#346]
In order to document the "deploy from customer image" deployment option we need to understand the behavior of authentication to a predefined custom image.
I think that the behavior is probably that the user and password that were set in the original image shoud be set on the undeployed-app and that way the user will be able to deploy the app and use the authntication on the app for connecting to the vm (QuaiX)

**Comment by tornizanQ** [comment]
Will check on windows machine, later will try to preform again on linux, It seems to consume to much effort (the linux part)

**Comment by tornizanQ** [comment]
From what it seems it possible to create an vhd image from source other than azure.
If the image is generalized correctly the users custom user name and password determined from our app will work correctly.

**Comment by tornizanQ** [comment]
The process it self is still unknown.

**Comment by Shnitselon** [comment]
no documentation required
