### ISSUE TITLE
ARM template fails during installing of es & qx scripts

### ISSUE THREAD

**Issue by cohoren** [QualiSystems/Azure-Shell#356]
Both scripts fail with the same error: "repomd.xml does not match metalink for epel".
Please see attached logs for more info.

notes:
- this is unstable
- the TC automation tests sometimes fails because of this

[qualix_logs.zip](https://github.com/QualiSystems/Azure-Shell/files/696028/qualix_logs.zip)
[execution_server_logs.zip](https://github.com/QualiSystems/Azure-Shell/files/696029/execution_server_logs.zip)

**Comment by TomerAdmon** [comment]
@cohoren  - can you add error message and/or logs?

**Comment by alexazarh** [comment]
The template still fails. Attached logs.

[qualix_logs.zip](https://github.com/QualiSystems/Azure-Shell/files/716582/qualix_logs.zip)
[execution_server_logs.zip](https://github.com/QualiSystems/Azure-Shell/files/716583/execution_server_logs.zip)

**Comment by TaiTheGreat** [comment]
Templates now deploy successfully
