### ISSUE TITLE
Handle Inbound ports configuration in the NSG

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#36]
1. Add attribute to the deployment service "Inbound Ports" (it already exists in the AWS Shell)
2. Implement the same functionality like in the AWS Shell. The logic to parse already exists in the AWS shell. 
   Need to determine the priority for new rule on the fly based on the next available priority. This section in the code should be atomic in order to guarentee a unique priorety per each rule when deploying.
- Source: "Any"
- Destiantion: Private IP of the deployed app, no need to use  "/32" CIDR notation as azure accepts a single IP address
- Protocol: UDP/TCP from attribute value
- Port: from attribute value
- Priority: Minumun priorety 1000. Increase between rules in priority will be 5. Example: 1000, 1005, 1010...

Syntax for specifying ports is a semicolon separated list:
protocol[tcp(default)/udp]:port[single/range]

example: 80,443:tcp,200-220:udp
1. If no public IP than the NSG rule cannot be created. Need to add a valiadation before creating the VM and throw an exception if the "Inbound Ports" attribute is not empty and "Add Public IP" is false.

Note: "Outbound Ports" attribute is redundant

**Comment by tornizanQ** [comment]
@menib @TomerAdmon , Just to be clear, the Outbound port should attribute be removed from the app?

**Comment by tornizanQ** [comment]
[testplan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=156071)

**Comment by tornizanQ** [comment]
https://github.com/QualiSystems/Azure-Shell/issues/203

**Comment by tornizanQ** [comment]
#203 #202 related bugs

**Comment by yairbb** [comment]
@tornizanQ 

Pls add link to the test plan .  Tag already exist
