### ISSUE TITLE
error message from driver not self explaining enough

### ISSUE THREAD

**Issue by EvgenyKhaliper** [QualiSystems/Azure-Shell#363]
Happened during discovery of cloud provider. From this message it is hard to understand that these subnets are already in use and must be added to exclude or automatically added to exclude if we already know they are in use.
![2](https://cloud.githubusercontent.com/assets/1864146/21854336/0423e1d6-d823-11e6-8d42-d7ee1dbb7e84.png)

**Comment by alexazarh** [comment]
@TomerAdmon - we need to update the error message to be more clear. It should clearly stated that the existing subnets should added to the "Networks In Use" field.

**Comment by TomerAdmon** [comment]
"The following subnets <subnets> were found under the 'sandbox' VNet in Azure and should be set in the "Network In Use" field."

@Shnitselon - what do you say?

**Comment by Shnitselon** [comment]
nice
