### ISSUE TITLE
ADDITIONAL MGMT NETWORKS - should be optional but is mandatory

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#366]
ADDITIONAL MGMT NETWORKS should be optional attribute

**Comment by TaiTheGreat** [comment]
@apiddubny  This is still reproducing for Tor and me with a new build and a new package. Any ideas?

**Comment by apiddubny** [comment]
@TaiTheGreat 
do you have some logs for failed deployment?

**Comment by TaiTheGreat** [comment]
turns out it was just not checked in to the develop yet. verified now.
