### ISSUE TITLE
Public IP Type attribute description update

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#370]
the new description as described in confluence

Static Public IP Type ensures that the VM always uses the same public IP. By default, Public IPs are dynamic and their address may change when the VM is powered off.

**Comment by GilGald** [comment]
@TomerAdmon  add more info please

**Comment by TomerAdmon** [comment]
@GilGald - just update the current description of the "Public IP Type" attribute, to the one described above and also described in the confluence page.

"Static Public IP Type ensures that the VM always uses the same public IP. By default, Public IPs are dynamic and their address may change when the VM is powered off."
