### ISSUE TITLE
Delete Sandbox VMs on Teardown (Cleanup Connectivity)

### ISSUE THREAD

**Issue by menib** [QualiSystems/Azure-Shell#38]
In Azure we should use the resource group to delete all objects at once

**Comment by yairbb** [comment]
could you pls specify which objects shell be deleted ?

**Comment by GilGald** [comment]
**We should delete the subnet from the Management resource group.

**Comment by tornizanQ** [comment]
Is there some list of all the objects that should be deleted when the teardown is running? @menib

**Comment by tornizanQ** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157096]

**Comment by tornizanQ** [comment]
Blocked by #https://github.com/QualiSystems/Azure-Shell/issues/146
