### ISSUE TITLE
Azure tenant discription in the discovery form is missing a mention about help center

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#382]
Azure tenant description in the discovery form is missing a paragraph

The description as writen in confluence
"The Azure tenant Id that is associated with your Azure Active Directory (AAD) instance. For example: ccd13026-98e3-4e90-01f4-28e2afdf3213.
The tenant ID is created for the Active Directory and can be retrieved when creating the Azure API web application or retrieved from Azure CLI. For more information, see the "Configure Azure API to work with CloudShell" article in the CloudShell online help."

**Comment by alexazarh** [comment]
@TomerAdmon please provide updated description

**Comment by TomerAdmon** [comment]
this is the description.
also described in confluence: http://confluence.quali.com/pages/viewpage.action?pageId=43253911

The Azure tenant Id that is associated with your Azure Active Directory (AAD) instance. For example: ccd13026-98e3-4e90-01f4-28e2afdf3213.
The tenant ID is created for the Active Directory and can be retrieved when creating the Azure API web application or retrieved from Azure CLI. For more information, see the "Configure Azure API to work with CloudShell" article in the CloudShell online help.

**Comment by tornizanQ** [comment]
There is a problem with the text of the description, it is not appears in the 'i' button in the portal
