### ISSUE TITLE
Azure Client ID discription in the discovery form is missing a mention about help center

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#385]
Azure Client ID discription in the discovery form is missing a mention about help center or where to find the help

**Comment by alexazarh** [comment]
@TomerAdmon please provide updated description

**Comment by tornizanQ** [comment]
The description is missing in the confluence page  http://confluence.quali.com/pages/viewpage.action?pageId=18514287

**Comment by TomerAdmon** [comment]
The "Client Id" attribute was renamed to "Azure Application Id" with the description: Application Id associated with the Azure API application. The application ID allows CloudShell to access the Azure API and is generated as part of the web application’s configuration process. For more information, see the "Configure Azure API to work with CloudShell" article in the CloudShell online help.

also described in confluence: http://confluence.quali.com/pages/viewpage.action?pageId=43253911

**Comment by tornizanQ** [comment]
The description should include the last part also:
" article in the CloudShell online help."
