### ISSUE TITLE
Rename client Id & Azure Secret

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#387]
since Azure moved to the new Portal and also changed the terminology, we need to align.
Please rename the following:
Client Id => Azure application Id
Azure Secret => Azure Application key

description was updated also: 
http://confluence.quali.com/pages/viewpage.action?pageId=18514287

**Comment by Shnitselon** [comment]
updated documentation

**Comment by alexazarh** [comment]
The name of new attributes with the correct case are:

Client Id => Azure Application ID
Azure Secret => Azure Application Key
