### ISSUE TITLE
Public IP in Azure

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/Azure-Shell#39]
Handle the creation  of the IP (static \Dynamic)
if add public IP is set to true we need create an IP.

Deployment  option attributes:
"Public IP Type"  - string ("Static" or "Dynamic")
"Add Public IP"  - bool, default value is False

**Comment by alexazarh** [comment]
@apiddubny Please add restricted values to the "Public IP Type" attribute. It will make the UX better.

**Comment by apiddubny** [comment]
@alexazarh 
Restricted values? Do you want me to add server-side validation?

**Comment by alexazarh** [comment]
@apiddubny 
No server side :)
There is an example how to do it in the vCenter shell for the "shutdown method" attribute. Its called "AllowedValues" in the datamodel xml.

**Comment by apiddubny** [comment]
@alexazarh
Ok, got it. I will add it

**Comment by apiddubny** [comment]
@alexazarh 
Should I add default value for this attribute?

**Comment by alexazarh** [comment]
Sure, lets set "Dynamic" as default

**Comment by tornizanQ** [comment]
as part of  #3
