### ISSUE TITLE
QualiX - new controller link results in sorry page

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#394]
1. Have a QualiX vm ready.
2. Create a sandbox with an Azure VM that can connect via the workspace.
3. Use the GetSandboxComponents API method to receive the new controller link.
4. Paste it into a web page.

BIR if you receive an error 500 (robot page) after logging in (or immediately if you're already logged in).

**Comment by TaiTheGreat** [comment]
Logs can be found here: \\qsnas1\Shared\TaiM\QualiX 2.4

**Comment by TaiTheGreat** [comment]
This is due to the expiry time of the generated link.  Managed to have it work. Cancelling the bug.

**Comment by TomerAdmon** [comment]
@TaiTheGreat - don't you think we should provide longer expiration time? or at least specify the "link is not valid anymore" in the robot page? 
i think that in the Sandbox API scenario, it will take the user more then 60 sec to copy/paste the link from place to place....

**Comment by TaiTheGreat** [comment]
@TomerAdmon 
That depends, will users actually use the sandbox API manually? or just via their automation? if there's a chance they'll use it manually then I agree we should provide an error stating that the link is expired and a new one is required. 
Regarding the expiration time, I'm not sure - wasn't the current time chosen due to security?
