### ISSUE TITLE
vCenter: Unable to deploy custome image

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#398]
STR
Create an custome image, you can use the provided imagein: \\qsnas1\Shared\Tor\TestDS
Add the app to an environment 
Reserve the environment 

BIR
The app didn't deployed with error

Error: CloudShellAPIError
Description: Command execution failed with error: 'Exception'.
Error description: error deploying image with the args: C:\Program Files\VMware\VMware OVF Tool\ovftool.exe --noSSLVerify --acceptAllEulas --powerOffTarget --name=VmImage_876b0ce8 --datastore=SB-DS2 --vmFolder=Tor \\qsnas1\Shared\Tor\TestDS\TestDS.ovf vi://qualisystems%5Ctor.n:%2A%2A%2A%2A%2A%2A@192.168.42.110/QualiSB/host/QualiSB%20Cluster/Resources/LiverPool, error: Opening OVF source: \\qsnas1\Shared\Tor\TestDS\TestDS.ovf
The manifest validates
Error: cURL error: Couldn't connect to server
Completed with errors

**Comment by alexazarh** [comment]
@tornizanQ 
The reason that its not working is that the password has a special char, "#", in this case.
Please open a bug specifically for this (we will not fix it now but we want to have it in the backlog).
