### ISSUE TITLE
QualiX - caching issues

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#404]
In an Azure environment, have QualiX configured.

1. Create a linux VM. 
2. Connect via the new SSH controller.
3. Connect via the old RDP controller. 

BIR if you connect once more via the SSH controller.

**Comment by TomerAdmon** [comment]
@TaiTheGreat  - Can you try to repreduce on QualiX 2.3? we (@TCDooM ) are not sure if this is related to the QualiX app itself or to the new version / deployment we added in QualiX 2.4
