### ISSUE TITLE
QualiX - "missing qtoken" error even though qtoken is present

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#405]
In an Azure environment, have QualiX.

1. Create a Linux vm. 
2. Try to connect via the new VNC/RDP/ controllers. 

BIR if you receive a sorry page with the following error:
Missing Querystring parameter: qtoken

Even though the URL actually did pass the qtoken parameter.

**Comment by TomerAdmon** [comment]
@igoro1975 
@TCDooM 

QualiX new links should support RDP, SSH, VNC and Telnet out of the box. to do su, we need to pass the url provided in the ServerUniversalSetting and pass the parameters in the POST request to the autentication service that will provide a valide session.

**Comment by igoro1975** [comment]
@TomerAdmon links should be fixed in the universal settings. No bugs in the code.
