### ISSUE TITLE
Connecting a manual VxLan to a VM with allocated range bigger than 16,000,000 will return unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#406]
STR 
Have a Vxlan connected (just the cvc) to openstack VM
Change the vxlan id to: 16,000,001
Run connect all command from the vlan

BIR
An unclear error returns 
** If connecting the vm from the cvc itself a normal error returned

**Comment by GilGald** [comment]
The error message with the stack trace will still be displayed but we will append the original error message to it.

**Comment by tornizanQ** [comment]
This is the error that still appears:
![image](https://cloud.githubusercontent.com/assets/17527106/22322665/552f51bc-e3a6-11e6-99d9-183d2c44eb61.png)

I still don't see the original error message.
