### ISSUE TITLE
QualiX: secure password

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#407]
customer should be able to set a link inside ServerUniversalSetting and to user the key-work "secure" instead of the password attribute.
in the flow, we should find password=secure and replace it with password={Password} so QualiX will handle the link the same but the password will not be visible at any time to the end user

**Comment by igoro1975** [comment]
@TomerAdmon in the conf: http://confluence.quali.com/pages/viewpage.action?pageId=43253943 we have in the VNC link password={Password} but if I am not mistaken it should be password=secure and this key-code we replace with the actual password.
Meanwhile, having password={Password} we get an exception. 
Please, add the explanation about this parameter.

**Comment by TomerAdmon** [comment]
@igoro1975  - The password=secure is optional. users can keep using the password={Password} way if they want. the "secure" key-word is just for advanced customers that doesn't want to expose the password in the url.
It's like that for all protocols, including SSH with out PEM file
