### ISSUE TITLE
Fix app naming

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#413]
- Replace white spaces with dashes (-) instead of removing the whitespace
- The 15 chars limit is applicable only for windows machines. No need to apply for Linux
- From the API is is possible to give the vm resource a different name form the computer name. So for Windows machines we will only truncate the computer name to 15 chars and keep the original app name for the vm resource. 
- The max length of the vm resource is 64 chars

**Comment by TomerAdmon** [comment]
Example Scenario:
Undeployed App name: CloudShell Portal Server-Windows
Deployed App name: cloudshell-portal-server-windows-dsfkj38
reosurce name: cloudshell-portal-server-windows-dsfkj38
hostname: cloudsh-dsfkj38
