### ISSUE TITLE
clean up stale data in Azure

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#423]
If the prepare connectivity fails than we can have   stale subnets left in Azure and it will block us from creating new reservations.

Need to add a hidden command on the CP that will clean up the stale resource. 
1. The command will get form the CloudShell API the list of active reservations
2. Find the Azure subnets that are not part of the any active reservation.
3. Remove stale subnets. If subnet does have any connected devices that we can remove the subnet directly. If subnet has connected devices than we need to find the relevant resource group and first delete it before deleting the subnet.
4. The operation must be atomic in such a way that it will block and prepare/cleanup connectivity operations.

**Comment by apiddubny** [comment]
we should also take into account "Networks In Use" attribute and don't delete subnets,  listed there

**Comment by alexazarh** [comment]
1. This cleanup will be part of the prep conn operation
2. We want to do a more specific cleanup and only fix the subnet that is taken at the moment. This is less destructive approach.
3. Add an attribute on the CP that will control this behavior. Attribute name: TBD - @TomerAdmon
