### ISSUE TITLE
Azure Template: QualiX and Execution Server should be tagged

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#427]
Azure Template should tag the QualiX and Execution server with the folowwing tags:
Key: "CreatedBy"
Value: "CloudShell"

and 

Key:"Role"
Value: "Management"

like in AWS CloudFormation

**Comment by TomerAdmon** [comment]
From AWS CLoudFormation
{
"Key": "CreateBy",
   "Value": "CloudShell"
},
{
   "Key": "Role",
   "Value": "Management"
}

**Comment by apiddubny** [comment]
@TomerAdmon 
should we add these tags only for QualiX and Execution server VMs or for the all related to them resources (networks, IPs, custom scrips)?
