### ISSUE TITLE
Change the session creation of the clients in Azure to be Singelton

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/Azure-Shell#43]
-In the deploy_azure_vm when we are creating a new client (using the Azure client factory) we are creating it for each and every operation .this needs to be done only for the 1st call for a method.

-Another thing that we need to check is that when changing the credentials for the client
the creation of client needs to take it into account.
(we should check that the session created with the given credentials).

**Comment by GilGald** [comment]
@alexazarh

**Comment by apiddubny** [comment]
@GilGald 
Azure clients use tokens for requests. With this new behavior we can easily get TokenExpiredError exception

**Comment by alexazarh** [comment]
@apiddubny That's a valid point. Do we know for how long a token is valid in Azure?

**Comment by apiddubny** [comment]
@alexazarh 
Need to investigate.  But there is also an option to provide auto refresh token url, which can automatically refresh access tokens

**Comment by alexazarh** [comment]
@apiddubny Did you found anything interesting?
