### ISSUE TITLE
Add validation on cloud provider autoload

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#58]

**Comment by yairbb** [comment]
@alexazarh @TomerAdmon 

Pls provide more description and details.

**Comment by alexazarh** [comment]
As a user I want to get feedback from the portal when I input data into attributes to know if the data is valid.

We need to do the following validations:
1. Successfully connect to Azure API 
2. Verify "Management Group Name" exists in provided Region and contains 2 vnets with correct tags
3. Verify "Instance Type" is valid if its not empty
4. If there is a subnet in the sandbox vnet and its cidr doesnt exit in "Networks In Use" than throw error do alert user about this. User will need to remove the subnet or add its cidr to the attribute.

**Comment by alexazarh** [comment]
Dont merge it to develop yet

**Comment by apiddubny** [comment]
@alexazarh 
Do we need "Instance Type" attribute for the cloud provider model?
We have the same attribute for our  deployment models

**Comment by alexazarh** [comment]
Yes we need it.
It should be used as a default vm size in case the attribute on the app is empty.

**Comment by tornizanQ** [comment]
Blocked by https://github.com/QualiSystems/Azure-Shell/issues/380
