### ISSUE TITLE
Cleanup attribute names and descriptions (data model finalizing)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#59]
###  Redundant attributes that should be removed on Deployment Service:
- Outbound Ports

### Redundant attributes that should be removed on Cloud Provider resource:
- Azure Mgmt Network ID
- Keypairs Location
- Storage Type
- AZURE MGMT VNET

### Cloud Provider resource attribute type changes:
- Azure Secret - change attribute type to Password

### Final attribute names and descriptions:
http://confluence.quali.com/pages/viewpage.action?pageId=18514287 (in progess)

**Comment by TomerAdmon** [comment]
"Azure Mgmt NSG ID" is also not needed anymore

**Comment by yairbb** [comment]
@TomerAdmon what about the Cloud Provider description ? is that final ? is that connected to that ticket ?

**Comment by TomerAdmon** [comment]
@yairbb - please see confluence page  http://confluence.quali.com/pages/viewpage.action?pageId=18514287

**Comment by yairbb** [comment]
@TomerAdmon 

I saw it. but, look at the header of this ticket . R U referring to both of them or to Data Model only ?

**Comment by TomerAdmon** [comment]
description is set within the datamodel.... this issue refers to all descriptions, attribute names and attribute existence in the shell.

**Comment by yairbb** [comment]
@TomerAdmon 

This description shell be changed to Azure instead of AWS  and the flavor too.: "The default AWS EC2 instance type. The instance type determines the CPU, memory, storage and networking capacity of the instance. For example "t2.large". in Instance Type field description

**Comment by yairbb** [comment]
[Testr Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157681)

**Comment by apiddubny** [comment]
@alexazarh 
we need "Azure Client ID" for Azure python client initialization

**Comment by alexazarh** [comment]
@apiddubny Need to handle password attribute decrypt or the entire system will break. Please update relevant PR.
