### ISSUE TITLE
Delete command for an Azure VM

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/Azure-Shell#6]
a hidden Delete command (interface should be similar to AWS and vCenter) that deletes the VM only from Azure

the flows that should be tested here are:
1. removal of VM from reservation should delete it from Azure and CloudShell
2. teardown should delete the VM from Azure and CloudShell
3. deletion from CloudShell inventory should delete the VM from Azure and CloudShell
4. test the scenario in which the VM is already deleted from Azure, shouldn't fail

notes:
- we shouldn't fail the command if the VM is already deleted
- sync, the command should be completed only once the VM is deleted
- no bulk support
- need to check how this story affects/relates to https://github.com/QualiSystems/AWS-Shell/issues/123 , talk with Shay
- this command should support a case when no command runs without reservation id

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156070)

**Comment by alexazarh** [comment]
bug #135
