### ISSUE TITLE
Documentation of Billing ("Aws budget" equivalent)

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#60]
Billing: 
- Every VM will have tags
- Clicking ‘View My Bill’ from the Azure interface leads to the azure subscription bill 
- Clicking the right subscription and then ‘Download usage details’ 
- From that page you can get a csv with two tables – 1. Billing Summary  2. Instance summary which contains the tags

**Comment by TomerAdmon** [comment]
tags we should have: 
CreatedBy = CloudShell
ReservationId = (cloudshell reservation id)
Owner = (name of the reservation owner)
Domain = (name of the reservation's domain)
Blueprint = (name of the reservation's environment)

Tags should be associated with all the entities we create (instance, security group, Subnet.....)

**Comment by yairbb** [comment]
@TomerAdmon @tornizanQ @alexazarh 

For what we need the BluePrint  Tag ? In Blueprint there are no deployments so there is no meaning to Billing.  It shell be Sandbox or reservation, no ?
 In case of reservation we have reservation id.
Pls   explain.

**Comment by TomerAdmon** [comment]
@yairbb - Customers would like to know what are the most useful blueprints they have...it makes sense...
this is how we implemented it also in AWS so we should be consistent.

**Comment by TomerAdmon** [comment]
please see issue #314  - we will change the "ReservationId" to use the new terminology "SandboxId"
