### ISSUE TITLE
Add "know n limitations" to release notes

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#61]
-- Limit for Network Security Groups (NSG) soft: 100, hard: 400 - we use 2 NSGs for QX & ES.

-- limit for Private IP Addresses per virtual network is 4096 ==> Concurrent apps: 4096 in CloudShell

-- Network Interfaces (NIC) soft: 300, hard: 10000

-- Concurrent Public IP addresses (dynamic) - 60 (soft) - need to contact support to increase, no hard limit.
Concurrent Reserved public IP addresses (static) 20 (soft) - need to contact support to increase, no hard limit

-- NSG rules per NSG - soft: 200, hard: 500 (if we have 2 rules per app on avg than we can have a max of 225 apps in a sandbox)

-- Cores quota - default is 30 per region, need to contact support to increase, max is 10K.

-- Number of storage accounts per subscription - soft: 200, hard: 250 - max number of sandboxes is 249 (one storage account is always used by management stuff). if we will add the support for premium storage accounts than the max number of sandboxes will be 124 (like in aws)

*** Concurrent sandboxes:  249 ***

------------------------------------------------

-- Extension script must be uploaded to a public location by the app designer, where in the azure portal the user only needs to browse for the file and azure will save it somewhere accessible by the VM.

**Comment by Shnitselon** [comment]
unclear sentence: if we will add the support for premium storage accounts than the max number of sandboxes will be 124 (like in aws)

does this mean we don't currently support permium storage accounts? will we support them ootb? is it configurable per customer?

**Comment by TomerAdmon** [comment]
@alexazarh - see @Shnitselon  comment above

**Comment by alexazarh** [comment]
@Shnitselon  We currently don't support permium storage accounts. If we will add support in the future than we can discuss the relevant limitations.

**Comment by Shnitselon** [comment]
@alexazarh cool. removed the note from the help

**Comment by Shnitselon** [comment]
@TomerAdmon now that it's documented, can it be moved to Done

**Comment by TomerAdmon** [comment]
@Shnitselon  - Sure!
![image](https://cloud.githubusercontent.com/assets/12639815/22240191/aa5f83e4-e222-11e6-8ff3-2240d48b7175.png)
