### ISSUE TITLE
Templates (Equivalent to cloud formation In AWS).

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#62]
1. Need to create a resource template JSON that will bootstrap our management network as described on the architecture page.
   http://confluence.quali.com/display/QP/Azure+Architecture+Design

Inputs:

- [ ] - Management Resource Group name (default value "Quali Management RG")
- [ ] - Mgmt VNET CIDR (default: 192.168.120.0/24)
- [ ] - CloudShell Server IP (for ES config)
- [ ] - CloudShell Server Username (for ES config)
- [ ] - CloudShell Server Password (for ES config)
- [ ] - On Premise CIDR (for VPN GW config)
- [ ] - VPN address (for VPN GW config)
- [ ] - VPN Shared Key (for VPN GW config. If empty need to generate a random key if possible)
- [ ] - QualiAgent Admin Username (default value: adminuser)
- [ ] - QualiAgent SSH public key
- [ ] - CloudShell Version (its a dropdown of supported versions)

Outputs:

- [ ] - Application Id (not implemented)
- [ ] - Application Secret (not Implemented)
- [ ] - VPN Gateway Public IP (only if the VPN will be selected)
- [ ] - QualiX Public IP 

https://blogs.msdn.microsoft.com/girishp/2015/06/16/azure-arm-templatestips-on-using-outputs/

General notes:
- Sandbox VNET CIDR is 10.0.0.0/8
- QualiAgent size "Standard_A3" (need to review this with Assaf)
- Also create an application with the Contributor role for the use of our Shell
- Installation of ES & QualiX (should be provided by Alex Abugov)
- Add a Deploy to Azure button to our GitHub:
  • Explanation: https://azure.microsoft.com/en-us/blog/deploy-to-azure-button-for-azure-websites-2/
  • Example: https://github.com/Azure/azure-quickstart-templates/tree/master/101-mobile-app-create

Resources:
- Azure Resource Manager (ARM) Templates Visualizer - http://armviz.io
- ARM Templates examples: https://github.com/Azure/azure-quickstart-templates

Open questions: 

1. How to use user data when deploying a VM
2. How to pass parameters from the template to the deployed VM  (e.g : the address of the server).

**Comment by alexazarh** [comment]
@menib Do we need to support both internal and external configuration like in aws?

**Comment by GilGald** [comment]
Resources to create:
1. VNET
2.Resource Group

**Comment by yairbb** [comment]
@TomerAdmon 
do we need to support internal and external in Azure like AWS ?

**Comment by GilGald** [comment]
# Deploy Json Template
## Create a virtual network
Create a sandbox and a management VNET's
Add a peering between the networks
Sandbox VNET CIDR is 10.0.0.0/8
### Related Inputs:

- Mgmt VNET CIDR(Default: 192.168.120.0/24)

## Create a resource group
Should be called :Quali Management RG
### Related Inputs:

## Create an NSG
### Related Inputs:

## Create a Storage
### Related Inputs:

## Create a VPN Gateway
### Related Inputs:

- On Premise CIDR (for VPN GW config)
- VPN address (for VPN GW config)
- VPN Shared Key (for VPN GW config. If empty need to generate a random key if possible)

## Create an instance with a EX and QS
Standard_A3
### Related Inputs:

- CloudShell Server IP (for ES config)
- CloudShell Server Username (for ES config)
- CloudShell Server Password (for ES config)
- QualiAgent Admin Username(default value: adminuser)
- QualiAgent SSH public key
- CloudShell Version(its a dropdown of supported versions)

**Comment by yairbb** [comment]
@alexazarh 

- QualiAgent Admin Username (default value: adminuser)
admin or adminuser ?

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=157384)

**Comment by TomerAdmon** [comment]
@GilGald  - Please note that we will support only standard storage in this release, so don't need to set a storageType parameter.

**Comment by TomerAdmon** [comment]
@yairbb @GilGald  - We will support two "Deployment flavors" - Internal and External. 
Internal - The QualiX instance Doesn't have Public IP
External - The QualiX instance have a Public IP

**Comment by alexazarh** [comment]
A guide on how to install ES on Centos 7.2 from the marketplace. It will be useful for creating the install script for ES instance.
http://confluence.quali.com/display/QRND/How+To+Install+Execution+Server+on+Linux+CentOS+7.2+From+Azure+Marketplace

**Comment by alexazarh** [comment]
@apiddubny 
1. Where the ES will be installed? The script uses relative path so its not clear.
2. Is it possible to add logs to the install script so it will be possible to debug it if something fails?

**Comment by TomerAdmon** [comment]
Hi Gil, please use those names & descriptions
[Azure Template descriptions.DOCX](https://github.com/QualiSystems/Azure-Shell/files/644476/Azure.Template.descriptions.DOCX)

**Comment by TomerAdmon** [comment]
Please set a Test plan review meeting then the test plan is ready

**Comment by GilGald** [comment]
This is the list of the new inputs names after the renaming:

![screenshot_1](https://cloud.githubusercontent.com/assets/15359652/22285343/ef2a875e-e2f3-11e6-93a7-e74150fdbe83.jpg)
