### ISSUE TITLE
Inbound Ports parameter applies only for last value in case list of ports

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/Azure-Shell#624]
### Issue details

Inbound Ports parameter can be configured for several ports. In case configuring list of Ports only the last value will apply to resource.

### Steps to reproduce

1. Create new Blueprint 

2. Add Azure app with follow parameters:
![image](https://user-images.githubusercontent.com/59359491/84140841-e42aa500-aa5a-11ea-9d3e-3577b3aebecb.png)

3. Reserve Blueprint

4. Observe NSG_sandbox_all_subnets in Microsoft Azure Portal

### Actual Result:
![image](https://user-images.githubusercontent.com/59359491/84141143-5f8c5680-aa5b-11ea-88e5-85f9fe29f581.png)

### Expected Result:
Must be configured both ports from Azure app.

**Comment by apiddubny** [comment]
done
