### ISSUE TITLE
Deleting VM its data disks should be deleted

### ISSUE THREAD

**Issue by igoro1975** [QualiSystems/Azure-Shell#65]
http://stackoverflow.com/questions/38400740/how-to-delete-a-disk-with-azure-sdk-for-python

**Comment by alexazarh** [comment]
There is an option to delete the disk from the CLI. We need to check what rest api the CLI calls and try to call it directly.
Another approach can be to access the storage account directly and delete the stale disk

**Comment by apiddubny** [comment]
Deletion of VM Image VHD disk supported only in Virtual Machines (classic) REST
https://msdn.microsoft.com/en-us/library/azure/dn499769.aspx

We are using this endpoint, and there is no such option
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines?redirectedfrom=MSDN#VirtualMachines_Delete

**Comment by tornizanQ** [comment]
As it seems there is still data in the container
