### ISSUE TITLE
Deploy a custom image

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#66]
- New deployment option for custom image
- Customer prepares the vm and uploads all custom images to a single storage account under the management resource group
- When deploying start copy the image to the reservation storage account. If the save image is used by more than one app than we need to copy the image only once.
- Instead of the 3 image identifier attributes that we have in the regular deployment service need to add an attribute "Image URN".

Article about Upload and create a Linux VM from custom disk image:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-upload-vhd/

**Comment by alexazarh** [comment]
Before implementing this story we need verify #66

**Comment by alexazarh** [comment]
Need to add an attribute "Image OS Type"

**Comment by yairbb** [comment]
@alexazarh  what did you meant "Before implementing this story we need verify #66" ?

we R on 66....

**Comment by alexazarh** [comment]
test plan needed

**Comment by alexazarh** [comment]
Sorry, #69  :)

**Comment by yairbb** [comment]
@TomerAdmon 

[]Test Plan(http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=157794)

**Comment by TomerAdmon** [comment]
error messages:
* if the image urn was not found, the user should get a popper error message: required image urn was not found.
