### ISSUE TITLE
Update deployment option to support "Cloud Providers" selection in the apps page

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#70]
The code should be backwards compatible

**Comment by tornizanQ** [comment]
the second deployment attribute is still exist

**Comment by TomerAdmon** [comment]
should also fix the "Custom image"

**Comment by tornizanQ** [comment]
@igoro1975 did you merge it to 7.2 to the new naming conventions of the apps, "Azure VM From Marketplace", "Azure VM From Custom Image"?

**Comment by igoro1975** [comment]
@tornizanQ should I merge it? I thought that the change should be done only in Trunk (7.2).

**Comment by igoro1975** [comment]
Besides the changes in Python some changes should be done on the Quali server. I added these changes on the server a minute ago. Cloud provider name changed to "Microsoft Azure". @tornizanQ  @alexazarh
