### ISSUE TITLE
Add Custom Tags attribute to all deployment option

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/Azure-Shell#72]
We need to let the user define custom tags. Up to 9 custom tags. Because Azure limit is 15 and we already use 6 tags for every object.

The custom tags should be applied to the VM and all related objects that are created during the app deploy

Add an attribute "Custom Tags" that will support the following syntax (comma separated list):
[TagName]=[TagValue], [TagName]=[TagValue]
Example:
Tag1=Val1, Tag2=Val2

**Comment by TomerAdmon** [comment]
validations - if the content of the attribute doesn't fit the above syntax we should fail the deploy of the app and throw a message to the user (output console) that the custom tags defined on this app were invalid. this should be shown both when deploying a single app or deploying apps as part of the Setup.

**Comment by alexazarh** [comment]
Dont merge it to develop before we create a release branch

**Comment by Costya-Y** [comment]
Issue moved to [QualiSystems/Azure-Shell-2G #12](https://github.com/QualiSystems/Azure-Shell-2G/issues/12) via [**ZenHub**](https://www.zenhub.com/)
